# Generated by Django 4.0.4 on 2022-05-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_auto_20210902_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
