# Generated by Django 4.0.4 on 2022-05-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_alter_customersignup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='address',
            field=models.CharField(blank=True, default='Robert Itinde', max_length=250, null=True),
        ),
    ]
